services:
    imgResize.post.persist:
       class: Weysan\DoctrineImgBundle\Listener\UploadDoctrineListener
       arguments: ["@service_container"]
       tags:
           - { name: doctrine.event_listener, event: preUpdate, connection: default }
           - { name: doctrine.event_listener, event: prePersist, connection: default }
