services:
#    weysan_doctrine_img.example:
#        class: Weysan\DoctrineImgBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    imgResize.post.persist:
       class: Weysan\DoctrineImgBundle\Listener\UploadDoctrineListener
       tags:
           - { name: doctrine.event_listener, event: preUpdate, connection: default }
           - { name: doctrine.event_listener, event: prePersist, connection: default }
