language: php

php:
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=dev-master
  
before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpunit --coverage-text
